dist: trusty
sudo: required
group: edge
env:
  global:
    - secure: G4MhQVAEjH2tLoO2Ep9icDvLyjCcrx8iJmzuRXU6R8fqF0BSK3a5vn0wrzI9yv2CscOapo+hXJR06UEF6OULSduklFvVdNLccp6yYvkc/l9YXgxd6bJrf1qpRT1Rv4GtF5ZrFFGQMTWUL2EQ0ssG7Sq+Mg+5Zc/RBX5EFhwUkJ1lkfyZB0deTY2g1QERDu5+n+7SZnV/AtsuAicuH1fQTvzOg5f1O9Ium0vFbkUUTgkaES8WNicsbUkvB/l4TF+wkEG2USr08gHCxyTSfF0ZwLGGvOgG3BU/N0e5s6IABm82Lc6JgxtCfBsPJ1Wjx3/Hi0jYcnYO+Py17WsyBhZxkECbK1vZxVqKeXOVacKRqxHDqEku5g5NJLbrGR1z5PdV0CTKTR0MwSVACJ6cied/8yB9GBM26/cDOSkQJz7PJlJA9HmzZB6/v/j9NgL7ncf5rke+/gczHPrA5fMPlGjPFLyWF1Az3+9MkKnldlOYHQ9VPjdaqkffuhAcAAG1wZa9udRbLKPhxQpZV8mn5+dlWPdmq6uAMaSS7LD1XPf1yI1H+YeTns2eCW0wE/wAKsTiHkkx3OzuBq7Kn/wAuWgZ30Uj4l5idTJTiSUpNSZEfArJAmZeG9Y6UZvuuT0U2RkS+Xf6DvkmeQbTm3RdwCejrDutXQQsyD15kCqBVaypeHM=

services:
  - docker

script:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_TAG

after_success:
  - docker login -u kuzzleteam -p $DOCKER_PASSWORD
  - bash build-docker-images.sh
